<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="DESKTOP-TEA6TKC" name="AppiumFramework.Demo1" tests="6" failures="0" timestamp="2021-01-27T23:20:40 IST" time="0.017" errors="1">
  <testcase name="testcase1" time="0.000" classname="AppiumFramework.Demo1">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <system-out/>
  <testcase name="testcase5" time="0.000" classname="AppiumFramework.Demo1">
    <skipped/>
  </testcase> <!-- testcase5 -->
  <system-out/>
  <testcase name="testcase3" time="0.000" classname="AppiumFramework.Demo1">
    <skipped/>
  </testcase> <!-- testcase3 -->
  <system-out/>
  <testcase name="testcase2" time="0.000" classname="AppiumFramework.Demo1">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <system-out/>
  <testcase name="testcase4" time="0.000" classname="AppiumFramework.Demo1">
    <skipped/>
  </testcase> <!-- testcase4 -->
  <system-out/>
  <testcase name="bt" time="0.017" classname="AppiumFramework.Demo1">
    <error type="java.io.IOException" message="Cannot run program &quot;C:\Users\VikasGundewar\Desktop\Mobile&quot;: CreateProcess error=2, The system cannot find the file specified">
      <![CDATA[java.io.IOException: Cannot run program "C:\Users\VikasGundewar\Desktop\Mobile": CreateProcess error=2, The system cannot find the file specified
at java.lang.ProcessBuilder.start(Unknown Source)
at java.lang.Runtime.exec(Unknown Source)
at java.lang.Runtime.exec(Unknown Source)
at java.lang.Runtime.exec(Unknown Source)
at AppiumFramework.Capability.startEmulator(Capability.java:39)
at AppiumFramework.Capability.capabilities(Capability.java:56)
at AppiumFramework.Demo1.bt(Demo1.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:617)
at org.testng.TestRunner.beforeRun(TestRunner.java:607)
at org.testng.TestRunner.run(TestRunner.java:578)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
at java.lang.ProcessImpl.create(Native Method)
at java.lang.ProcessImpl.<init>(Unknown Source)
at java.lang.ProcessImpl.start(Unknown Source)
... 31 more
]]>
    </error>
  </testcase> <!-- bt -->
  <system-out/>
</testsuite> <!-- AppiumFramework.Demo1 -->
